### ISSUE TITLE
工信部和百度是一家的吧

### ISSUE THREAD

**Issue by cubiccm** [Chrogeek/chrogeek.github.io#1]
感觉举报并没有什么l用，他们会不回应或者找各种借口拒绝你的
（而且它主要处理“不良与垃圾信息”
这种感觉直接找客服靠谱点
像tx这种公司根本不给你注销帐户的入口
新浪微博客服告诉我不想用就不用 放到那就好了
而且最初Google退出中国大陆不也是有百度的因素
_（趁早Google为上_

**Comment by Chrogeek** [comment]
依次回复：
1. 工信部约谈过百度（今年1月），所以从这个角度讲大概还不算是一家的吧
2.「主要处理“不良与垃圾信息”」不假，然而除此之外就没处举报了……（而且我也是看了某些没提报道才这么做的）
3. 客服才是最不靠谱的，他们互相推脱（已经试过了）
4. 微信还是能注销的，条件比百度简单太多了（qq就算了）
5. 新浪微博现在也能注销了
6. google也作恶呀（滑稽）没有哪家企业不作恶的

**Comment by Chrogeek** [comment]
这篇文章暂时撤了，所以这个 issue 我要关掉了
